language: python
python: 
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


# commands to install dependencies
install:
  - make pip-install
  - make install-pre-commit

# command to run tests
script:
  - mypy --ignore-missing-imports .